version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  test:
    executor:
      name: node/default
      tag: '14'
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
      - run: npm run test
  build:
    executor: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run build

  deployment:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: |
          echo "Deployment"
          /home/circleci/.fly/bin/flyctl --app ${APP_NAME} deploy
        
workflows:
  build:
    jobs:
      - build
  deployment:
    jobs:
      - deployment:
          pre-steps:
            - run: curl -L https://fly.io/install.sh | sh
            - run: /home/circleci/.fly/bin/flyctl auth token $FLY_API_TOKEN
            - run: curl -o prod.env ${ENV_URI}
