version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  test:
    executor:
      name: node/default
      tag: '14'
    steps:
      - checkout
      - node/install-packages:
        cache-path: ~/project/node_modules
      - run:
        command: npm run test
        name: Testing
  build:
    executor:
      name: node/default
      tag: '14'
      steps:
        - checkout
        - run: 
          command: npm run build
          name: Project Build

  deployment:
    machine:
      image: ubuntu-1604:201903-01
    requires:
      - build
    pre-steps:
      - run: |
        curl -L https://fly.io/install.sh | sh
        /root/.fly/bin/flyctl --help
    steps:
      - checkout
      - run: |
        echo "Deploy to staging server"
        curl -o prod.env $ENV_URI
        /root/.fly/bin/flyctl auth token $FLY_API_TOKEN
        /root/.fly/bin/flyctl --app  deploy
      - run: echo "Successfully Deployed Application"
        
workflows:
  build-and-test:
    jobs:
      - test
      - build
  deployment:
    jobs:
      - deployment

        
