on:
  release:
    types: [ published ]

name: 🚀 Deployment

jobs:
  deployment:
    name: "Deployment"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fly.io Deployment
        uses: superfly/flyctl-actions@1.1
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: deploy -i registry.fly.io/${{ secrets.FLY_APP_NAME }}