on: [ push, pull_request ]

name: Testing
    
jobs:
  test:
    name: "🧪 Testing"
    runs-on: ubuntu-latest
    environment: Test
    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      APP_NAME: ${{ secrets.APP_NAME }}
      KEY: ${{ secrets.KEY }}
      TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: App Testing
        run: |
          npm i
          node ./scripts/secrets --write
          npm run test:e2e
  